Document: ddeploy
Title: Debian ddeploy Manual
Author: <insert document author here>
Abstract: This manual describes what ddeploy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ddeploy/ddeploy.sgml.gz

Format: postscript
Files: /usr/share/doc/ddeploy/ddeploy.ps.gz

Format: text
Files: /usr/share/doc/ddeploy/ddeploy.text.gz

Format: HTML
Index: /usr/share/doc/ddeploy/html/index.html
Files: /usr/share/doc/ddeploy/html/*.html
